### PR TITLE
Adding Async support for S3, so you can use it with spring-cloud-aws.

### PR DESCRIPTION
**Pull request by varunmehta**
*Issue: https://github.com/awslabs/amazon-sqs-java-extended-client-lib/issues/5 

*Description of changes:*
Adding Async support for S3, so you can integrate it with spring-cloud-aws @aws-aminsuzani 

The change has to be done at the core library level for the teams to use it; https://github.com/spring-cloud/spring-cloud-aws/issues/167 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dexwest** [comment]
I need this is there any chance this is close to be merged?

**Comment by ajross** [comment]
I suggest this isn't quite ready to be merged.  I've been trying to use it and some additional functionality should be added to support encrypted S3 buckets (though arguably that's an issue with the AWS `ExtendedClientConfiguration` class).  Additionally, in the current implementation, when calling the constructor with your own `ExtendedClientConfiguration`, the config isn't passed through to the client that's used for sending the message.  A change needs to be made to the constructors in the `AmazonSQSAsyncExtendedClient` to call `super(sqsClient, extendedClientConfig)`.  If I get it working I'll see if I can contribute the change back.

**Comment by sreekanth-tf** [comment]
@ajross may I know, is there any update?

**Comment by richardsmithsfdc** [comment]
I see this was attempted a few times, and I wanted to add my attempt into the ring here. This is a draft PR to add async support to extended client library: https://github.com/awslabs/amazon-sqs-java-extended-client-lib/pull/79 , which is based on async support in payload offloading, for which I also created a PR: https://github.com/awslabs/payload-offloading-java-common-lib-for-aws/pull/19 .

This is a full async implementation, with design consistent with the sync implementation. It is accompanied by a full set of UTs, and I have locally done IT to verify that it works. 

If anyone is interested in this, please review the payload offloading PR first. Once that is committed, the new PR can be changed to ready state and also reviewed. 

I'll add this same comment to the original issue.

**Comment by ziyanli-amazon** [comment]
Thanks to @richardsmithsfdc the feature will be supported since `2.1.0`.

**Pull request closed without merging**
